/**
 * The email renderer: sender markup in, markup we are prepared to put in our own document out.
 *
 * ⛔ THIS INSTANCE IS DELIBERATELY NOT THE SHARED ONE. DOMPurify hooks are registered on an
 * instance and run for EVERY `sanitize` call on it. The app already registers two global hooks
 * (`addNoopenerHook`, `addProxiedImagesOnlyHook`) on the default instance, which is also what
 * sanitizes internal notes and comments — content with `ALLOWED_ATTR: []` that must not acquire
 * email behaviour. Hanging the style filter and class rewriter off that same instance would make
 * the note sanitizers depend on whether an email had been rendered first, which is the kind of
 * order-dependent coupling that passes every test and then behaves differently in the app.
 * So the email renderer owns a private instance; `emailRendererIsIsolated` in the tests holds
 * that line with a control.
 */
import createDOMPurify from 'dompurify';
import { filterDeclarations, prefixClasses } from './emailCss';

/**
 * Tags an email may use. Wider than the old thread allowlist because that list was written for
 * "a paragraph of text with a link" and email is not that: it is tables, nested divs, font tags
 * and headings, much of it generated by tools that have not changed since 2009.
 *
 * `style` and `link` are absent ON PURPOSE and are ALSO listed in `FORBID_TAGS` below — see the
 * comment there, removing the element is not the same as removing its text.
 */
export const EMAIL_ALLOWED_TAGS = [
  // Text flow
  'p',
  'br',
  'hr',
  'div',
  'span',
  'blockquote',
  'pre',
  'code',
  'address',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  // Inline marks, including the ones only email still uses
  'b',
  'i',
  'u',
  's',
  'strike',
  'del',
  'ins',
  'em',
  'strong',
  'small',
  'big',
  'sub',
  'sup',
  'font',
  'center',
  // Links and images
  'a',
  'img',
  // Lists
  'ul',
  'ol',
  'li',
  'dl',
  'dt',
  'dd',
  // Tables — the actual layout engine of email
  'table',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'td',
  'th',
  'caption',
  'colgroup',
  'col',
  // Figures
  'figure',
  'figcaption',
];

/**
 * Attributes an email may carry.
 *
 * ⛔ `background` is NOT here, and that is not an oversight. The `background` attribute on
 * `<td>`/`<table>` takes a URL and the browser fetches it — a read receipt that `proxyRemoteImages`
 * never looks at because it only rewrites `<img src>`. Same reasoning for `srcset` and `usemap`.
 * A sender wanting a cell background can say `background-color`, which survives, or
 * `background-image`, whose `url()` is rewritten through the proxy.
 */
export const EMAIL_ALLOWED_ATTR = [
  'href',
  'target',
  'rel',
  'src',
  'alt',
  'title',
  'dir',
  'width',
  'height',
  'style',
  'class',
  'align',
  'valign',
  'colspan',
  'rowspan',
  'bgcolor',
  'cellpadding',
  'cellspacing',
  'border',
  'nowrap',
  'color',
  'face',
  'size',
  'start',
  'type',
];

/**
 * ⛔ Without this, `ALLOWED_URI_REGEXP` DELETES every attribute in it.
 *
 * DOMPurify URI-checks every attribute it does not hold as URI-safe. This is the same trap that
 * silently removed `width`/`height` from every email until support-ui#404 — the config said the
 * dimensions came along and the sanitizer took them out. Every NON-URL attribute we add has to
 * be declared safe here or it is quietly dropped, and the failure looks exactly like "email CSS
 * just doesn't work".
 *
 * `style` and `class` are in this list because their VALUES are not URLs — they are filtered by
 * `filterDeclarations` and `prefixClasses` in the hook below, which is where their real guard is.
 */
const EMAIL_URI_SAFE_ATTR = [
  'width',
  'height',
  'style',
  'class',
  'align',
  'valign',
  'colspan',
  'rowspan',
  'bgcolor',
  'cellpadding',
  'cellspacing',
  'border',
  'nowrap',
  'color',
  'face',
  'size',
  'start',
  'type',
  'dir',
  'title',
  'alt',
];

export type EmailRenderContext = {
  /** The message the images belong to — the proxy URL is per event. */
  eventId: number;
  apiBaseUrl: string;
  /**
   * The workspace, which must ride IN the proxy path: the browser loads these URLs itself, so
   * the `X-Organization-Context` header never reaches the backend. See `proxyRemoteImages`.
   */
  organizationId?: number | null;
};

/** The image-proxy endpoint for one message. Kept identical in shape to `proxyRemoteImages`. */
export function imageProxyBase(context: EmailRenderContext): string {
  const { apiBaseUrl, eventId, organizationId } = context;
  return typeof organizationId === 'number' && organizationId > 0
    ? `${apiBaseUrl}/api/organizations/${organizationId}/messages/events/${eventId}/image`
    : `${apiBaseUrl}/api/messages/events/${eventId}/image`;
}

/**
 * The hook needs to know which message it is rendering, but hooks are registered once per
 * instance rather than per call. `sanitize` is synchronous and single-threaded, so the context
 * is set immediately before it and cleared in a `finally` immediately after — a hook can never
 * observe a context belonging to a different message.
 *
 * 🪤 If this ever becomes async, this breaks silently and cross-wires messages' image URLs.
 */
let activeContext: { proxyBase: string; eventId: number } | null = null;

let purifier: ReturnType<typeof createDOMPurify> | null = null;

function emailPurifier(): ReturnType<typeof createDOMPurify> {
  if (purifier) return purifier;
  const instance = createDOMPurify(window);

  instance.addHook('afterSanitizeAttributes', (node: Element) => {
    const context = activeContext;

    // Anchors: always open away from the console, never able to reach `window.opener`.
    // Set rather than checked — `ALLOWED_URI_REGEXP` removes `target`/`rel` before any hook
    // runs, so a hook that tested for them would test for something already deleted.
    if (node.tagName === 'A' && node.hasAttribute('href')) {
      node.setAttribute('target', '_blank');
      node.setAttribute('rel', 'noopener noreferrer');
    }

    if (node.hasAttribute('class')) {
      const prefixed = context
        ? prefixClasses(node.getAttribute('class') ?? '', context.eventId)
        : '';
      if (prefixed.length > 0) node.setAttribute('class', prefixed);
      else node.removeAttribute('class');
    }

    if (node.hasAttribute('style')) {
      const filtered = context
        ? filterDeclarations(node.getAttribute('style') ?? '', context.proxyBase)
        : '';
      // An empty `style=""` is noise in the DOM and reads as "the sender set nothing" when in
      // fact everything they set was refused. Remove the attribute instead.
      if (filtered.length > 0) node.setAttribute('style', filtered);
      else node.removeAttribute('style');
    }

    /**
     * Last line of defence on images. `proxyRemoteImages` rewrites `src` with a regex over
     * sender-controlled markup, and a regex over hostile HTML is a thing that can be wrong. By
     * this point the node is parsed, so there is no quoting or entity trickery left to hide
     * behind: anything not pointing at our proxy is removed, and a rewrite miss degrades to a
     * missing image rather than to a silent beacon.
     */
    if (node.tagName === 'IMG') {
      const src = node.getAttribute('src') ?? '';
      if (!context || !src.startsWith(context.proxyBase)) node.remove();
    }
  });

  purifier = instance;
  return instance;
}

/**
 * Sanitize one message's HTML for rendering inside our own document.
 *
 * `html` must ALREADY have been through `liftImageDimensions` and `proxyRemoteImages` — the
 * dimensions have to come out of `style` before the style filter sees it, and `src` has to be
 * rewritten before the image hook removes anything that is not proxied. Order matters and only
 * in that direction.
 */
export function sanitizeEmailHtml(html: string, context: EmailRenderContext): string {
  const instance = emailPurifier();
  activeContext = { proxyBase: imageProxyBase(context), eventId: context.eventId };
  try {
    return instance.sanitize(html, {
      ALLOWED_TAGS: EMAIL_ALLOWED_TAGS,
      ALLOWED_ATTR: EMAIL_ALLOWED_ATTR,
      ADD_URI_SAFE_ATTR: EMAIL_URI_SAFE_ATTR,
      /**
       * `mailto:` and `tel:` are here because this renders EMAIL. A signature's contact block
       * is mostly `mailto:` links, and the old `^https?:` pattern stripped every one of them —
       * the address rendered as dead text. Neither scheme can execute anything; `javascript:`,
       * `data:` and the rest stay refused, which the 'javascript: url is still refused' test
       * holds. An `<img src="mailto:…">` is meaningless and is removed by the image hook below
       * anyway, since it does not start with our proxy prefix.
       */
      ALLOWED_URI_REGEXP: /^(?:https?|mailto|tel):/i,
      /**
       * ⛔ DO NOT ADD `FORBID_CONTENTS` HERE. I did, as "defence in depth", and it was a real
       * regression: the option REPLACES DOMPurify's own default list rather than extending it,
       * and that default is much longer — it covers `svg`, `math`, `template`, `noscript`,
       * `plaintext`, `xmp` and more, which is the mXSS namespace-confusion surface.
       *
       * Measured, with a control: sanitizing
       * `<svg><desc>SVGTEXT</desc></svg><math><mi>MATHTEXT</mi></math><noscript>NOSCRIPTTEXT</noscript>`
       * yields `""` on the default and `"SVGTEXTMATHTEXTNOSCRIPTTEXT"` with the four-entry list
       * I had written. So the line intended to harden the config was the only thing letting
       * that content through. `emailHtml.forbidContents.test.ts` keeps it that way.
       *
       * `<style>`'s CSS text is dropped by that same default, which is what stops a stylesheet
       * being pasted into the message as visible text.
       */
      FORBID_TAGS: [
        'style',
        'link',
        'script',
        'base',
        'meta',
        'form',
        'input',
        'iframe',
        'object',
        'embed',
      ],
    });
  } finally {
    activeContext = null;
  }
}
